<a href="https://colab.research.google.com/github/Deepaksharma4124/Sql_Query_IMDB/blob/main/basics_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#importing libary
import numpy as np

In [5]:
#creating an array
a=np.array([1,2,3])

In [6]:
#finding the shape
a.shape

(3,)

In [7]:
a[0]

1

In [8]:
a[1]

2

In [9]:
a=np.array([[1,2],[4,5],[5,6]])

In [10]:
a

array([[1, 2],
       [4, 5],
       [5, 6]])

In [11]:
a.ndim

2

In [13]:
a.itemsize

8

In [14]:
#converting datatype
a=np.array([[1,2],[4,5],[5,6]],dtype=np.float64)

In [15]:
a

array([[1., 2.],
       [4., 5.],
       [5., 6.]])

In [17]:
a=np.array([[1,2],[4,5],[5,6]],dtype=np.complex)

<ipython-input-17-1b1305f1745d>:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.array([[1,2],[4,5],[5,6]],dtype=np.complex)


In [18]:
a

array([[1.+0.j, 2.+0.j],
       [4.+0.j, 5.+0.j],
       [5.+0.j, 6.+0.j]])

In [19]:
#creating zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
#creating ones
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.char.add(["hello","i hope "],["vaishnavi","you are doing good:p"])

array(['hellovaishnavi', 'i hope you are doing good:p'], dtype='<U27')

In [24]:
#multiply
np.char.multiply(["hello","vaishanavi"],3)

array(['hellohellohello', 'vaishanavivaishanavivaishanavi'], dtype='<U30')

In [28]:
#center
np.char.center("hello",20,fillchar="-")


array('-------hello--------', dtype='<U20')

In [31]:
#captilazion
np.char.capitalize("hello,how are you doing")

array('Hello,how are you doing', dtype='<U23')

In [32]:
#title
np.char.title("hello,how are you doing")

array('Hello,How Are You Doing', dtype='<U23')

In [33]:
#lower
np.char.lower("THIS IS NUMPY BASICS")

array('this is numpy basics', dtype='<U20')

In [34]:
#UPPER
np.char.upper("this is numpy basics")

array('THIS IS NUMPY BASICS', dtype='<U20')

In [35]:
#split
np.char.split("python is a top programming langugae")

array(list(['python', 'is', 'a', 'top', 'programming', 'langugae']),
      dtype=object)

In [36]:
#join 
np.char.join([":","-"],["day","date"])

array(['d:a:y', 'd-a-t-e'], dtype='<U7')

In [37]:
#replace
np.char.replace("python is a programmming language","python","java")

array('java is a programmming language', dtype='<U31')